import { OnInit, ElementRef, AfterViewInit, AfterViewChecked, EventEmitter, OnChanges } from '@angular/core';
import * as momentNs from 'moment';
export declare class DaterangepickerComponent implements OnInit, AfterViewInit, AfterViewChecked, OnChanges {
    show: boolean;
    menuTop: any;
    menuLeft: any;
    dateStr: string;
    title: string;
    activeItem: string;
    showCalendar: boolean;
    trigger: boolean;
    startDate: momentNs.Moment;
    endDate: momentNs.Moment;
    opens: string;
    start: any;
    end: any;
    outputFormat: any;
    format: string;
    minDate: any;
    maxDate: any;
    pill: false;
    ranges: any;
    startChange: EventEmitter<{}>;
    endChange: EventEmitter<{}>;
    open: EventEmitter<any>;
    complete: EventEmitter<any>;
    cEl: ElementRef;
    el: ElementRef;
    constructor();
    ngOnInit(): void;
    selectRange(range: any): void;
    setCurrent(): void;
    ngAfterViewInit(): void;
    ngAfterViewChecked(): void;
    toggleMenu(): void;
    renderText(start: momentNs.Moment, end: momentNs.Moment): void;
    triggerCalendar(): void;
    apply(): void;
    closeMenu(): void;
    detected(event: any): void;
    emitResult(): void;
    ngOnChanges(changes: any): void;
}
